const api = {
  token: localStorage.getItem('gather-token'),
  async request(path, options = {}) {
    const response = await fetch(`/api${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(this.token ? { Authorization: `Bearer ${this.token}` } : {}), ...(options.headers || {}) } });
    const data = await response.json();
    if (!response.ok) throw new Error(data.error || 'Something went wrong.');
    return data;
  }
};
let state = { user: null, posts: [], people: [], conversations: [], selectedConversation: null, filter: 'for-you' };
let inboxTimer;
const $ = (selector) => document.querySelector(selector);
const toast = $('#toast');
const spaceCatalog = { 'design-thinkers': { name: 'Design thinkers', color: 'amber', description: 'A thoughtful room for product ideas, visual systems, and the craft behind good work.', members: 248 }, 'weekend-runners': { name: 'Weekend runners', color: 'coral', description: 'Routes, race-day notes, gentle accountability, and the joy of moving outside.', members: 86 }, 'book-club': { name: 'Book club', color: 'mint', description: 'A slower conversation about the books that stay with us after the last page.', members: 124 } };
function applyTheme(theme) { document.documentElement.dataset.theme = theme; const dark = theme === 'dark'; $('#themeToggle').innerHTML = `<span>${dark ? '☀' : '☾'}</span>`; $('#themeToggle').setAttribute('aria-label', dark ? 'Switch to light theme' : 'Switch to dark theme'); toast.style.background = dark ? '#eef2e7' : '#252a2b'; toast.style.color = dark ? '#18201d' : '#d9f36a'; }
applyTheme(localStorage.getItem('gather-theme') || 'light');
function showToast(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 2400); }
function escapeHtml(value) { const node = document.createElement('div'); node.textContent = value; return node.innerHTML; }
function openUtility(title, eyebrow, content) { $('#utilityTitle').textContent = title; $('#utilityEyebrow').textContent = eyebrow; $('#utilityContent').innerHTML = content; $('#utilityBackdrop').hidden = false; }
function closeUtility() { $('#utilityBackdrop').hidden = true; }
function savedIds() { return JSON.parse(localStorage.getItem('gather-saved') || '[]'); }
let selectedPostImage = null;
function avatar(person, extra = '') { return person.profileImage ? `<span class="avatar ${extra} avatar-photo"><img src="${person.profileImage}" alt="${escapeHtml(person.name || 'Profile photo')}" /></span>` : `<span class="avatar ${extra}" style="background:${person.color || 'var(--lime)'}">${person.initials}</span>`; }
function resizeImage(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const scale = Math.min(1, 1000 / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', .78)); }; image.onerror = reject; image.src = reader.result; }; reader.onerror = reject; reader.readAsDataURL(file); }); }
function renderSpaces() { const spaces = JSON.parse(localStorage.getItem('gather-spaces') || '[]'); document.querySelectorAll('.custom-space').forEach((item) => item.remove()); spaces.forEach((space) => { const button = document.createElement('button'); button.className = 'space-item custom-space'; button.dataset.space = space.id; button.innerHTML = `<span class="space-dot ${space.color}"></span>${escapeHtml(space.name)}`; $('.rail-label').after(button); }); }
function joinedSpaces() { return JSON.parse(localStorage.getItem('gather-joined-spaces') || '[]'); }
function openSpace(id) { const custom = JSON.parse(localStorage.getItem('gather-spaces') || '[]').find((space) => space.id === id); const space = spaceCatalog[id] || custom; if (!space) return; const joined = joinedSpaces().includes(id); openUtility(space.name, 'YOUR SPACE', `<div class="space-detail"><span class="space-dot ${space.color}"></span><p>${escapeHtml(space.description || 'A new place to gather around a shared interest.')}</p><div class="space-stats"><strong>${space.members || 1}</strong><span>members</span><strong>${joined ? 'Joined' : 'Open'}</strong><span>status</span></div><button class="utility-action space-membership" data-space-action="join" data-space-id="${id}">${joined ? 'Leave space' : 'Join space'}</button><button class="sort-choice" data-space-action="feed" data-space-id="${id}"><strong>View space feed</strong><span>See conversations from this space</span></button></div>`); }
function setUser(user) { state.user = user; const avatars = [$('#profileButton .avatar'), $('.profile-card .avatar-large')]; avatars.forEach((node) => { node.innerHTML = user.profileImage ? `<img src="${user.profileImage}" alt="${escapeHtml(user.name)} profile photo" />` : user.initials; node.style.background = user.color; node.classList.toggle('avatar-photo', Boolean(user.profileImage)); }); $('#profileButton .profile-name').textContent = user.name; $('.profile-title h3').textContent = user.name; $('.profile-card-content p').textContent = user.handle; $('.profile-stats').innerHTML = `<span><strong>${user.following}</strong> following</span><span><strong>${user.followers}</strong> followers</span>`; $('.mobile-heading h1').textContent = `Good morning, ${user.name.split(' ')[0]}.`; }
function postTemplate(post, index) { const body = escapeHtml(post.text).replace(/(#\w+)/g, '<strong>$1</strong>'); const saved = savedIds().includes(post.id); return `<article class="post" style="animation-delay:${index * 60}ms" data-post-id="${post.id}"><div class="post-head">${avatar(post)}<div class="post-meta"><strong>${escapeHtml(post.name)}</strong><span>${post.handle} · ${post.time}</span></div><button class="post-menu" aria-label="More options">•••</button></div><div class="post-body"><p>${body}</p>${post.image ? `<img class="post-photo" src="${post.image}" alt="Image shared by ${escapeHtml(post.name)}" />` : ''}<div class="post-actions"><button class="like-button ${post.liked ? 'liked' : ''}" data-action="like"><span>${post.liked ? '♥' : '♡'}</span>${post.likes}</button><button data-action="comment"><span>◌</span>${post.comments}</button><button class="save-action ${saved ? 'saved' : ''}" data-action="save"><span>${saved ? '▣' : '▱'}</span></button><button data-action="share"><span>↗</span>${post.shares}</button></div></div></article>`; }
function renderFeed(source = state.posts) { let list = source; if (state.filter === 'following') list = list.filter((post) => post.following); if (state.filter === 'latest') list = [...list].reverse(); const query = $('#searchInput').value.toLowerCase().trim(); if (query) list = list.filter((post) => `${post.name} ${post.handle} ${post.text}`.toLowerCase().includes(query)); $('#feed').innerHTML = list.map(postTemplate).join('') || '<div class="post"><p>No stories found. Try another search.</p></div>'; }
function renderPeople() { $('#peopleList').innerHTML = state.people.map((person) => `<div class="person">${avatar(person)}<div class="person-info"><strong>${escapeHtml(person.name)}</strong><span>${escapeHtml(person.note || person.bio || '')}</span></div><button class="message-person" data-message-person="${person.handle}" aria-label="Message ${escapeHtml(person.name)}">✉</button><button class="follow-button ${state.user.followingHandles?.includes(person.handle) ? 'following' : ''}" data-person="${person.handle}">${state.user.followingHandles?.includes(person.handle) ? 'Following' : 'Follow'}</button></div>`).join(''); }
function renderConversations() { const existing = new Set(state.conversations.map((item) => item.handle)); const starters = state.people.filter((person) => !existing.has(person.handle)).map((person) => ({ ...person, preview: 'Start a new conversation', time: '' })); const list = [...state.conversations, ...starters]; $('#conversationList').innerHTML = list.map((item) => `<button class="conversation ${state.selectedConversation?.handle === item.handle ? 'active' : ''}" data-conversation="${item.handle}">${avatar(item)}<div><strong>${escapeHtml(item.name)}</strong><p>${escapeHtml(item.preview)}</p></div><time>${item.time}</time></button>`).join('') || '<p class="chat-empty"><small>No people to message yet.</small></p>'; }
function openComposer(kind = '') { $('#modalTitle').textContent = kind ? `Share a ${kind.toLowerCase()}` : 'What’s on your mind?'; selectedPostImage = null; $('#postImageInput').value = ''; $('#postImagePreview').hidden = true; $('#postImageLabel').textContent = 'Add an image to your post'; $('#modalBackdrop').hidden = false; $('#postText').focus(); }
async function loadApp() { const data = await api.request('/bootstrap'); state = { ...state, ...data, user: { ...data.user, followingHandles: data.people.filter((person) => data.user.followingIds?.includes(person.id)).map((person) => person.handle) } }; setUser(state.user); renderFeed(); renderPeople(); renderConversations(); renderSpaces(); $('#authScreen').style.display = 'none'; $('.app-shell').classList.add('ready'); }
let registerMode = false;
function refreshAuthMode() { $('#authTitle').textContent = registerMode ? 'Join the conversation.' : 'Welcome back.'; $('#authSubtitle').textContent = registerMode ? 'Create an account and find your people.' : 'Log in to pick up where you left off.'; $('#nameField').hidden = !registerMode; $('#nameInput').required = registerMode; $('#authSubmit').innerHTML = registerMode ? 'Create account <span>↗</span>' : 'Log in <span>↗</span>'; $('#authSwitch').innerHTML = registerMode ? 'Already have an account? <button type="button">Log in</button>' : 'New to Gather? <button type="button">Create an account</button>'; $('#authSwitch button').addEventListener('click', () => { registerMode = !registerMode; refreshAuthMode(); }); }
$('#authSwitch button').addEventListener('click', () => { registerMode = true; refreshAuthMode(); });
$('#authForm').addEventListener('submit', async (event) => { event.preventDefault(); $('#authError').textContent = ''; const payload = { name: $('#nameInput').value, handle: $('#handleInput').value, password: $('#passwordInput').value }; try { const result = await api.request(registerMode ? '/auth/register' : '/auth/login', { method: 'POST', body: JSON.stringify(payload) }); api.token = result.token; localStorage.setItem('gather-token', result.token); await loadApp(); startInboxPolling(); } catch (error) { $('#authError').textContent = error.message; } });
$('#composerTrigger').addEventListener('click', () => openComposer()); $('#postButton').addEventListener('click', () => openComposer()); document.querySelectorAll('[data-compose]').forEach((button) => button.addEventListener('click', () => openComposer(button.dataset.compose))); $('#closeModal').addEventListener('click', () => { $('#modalBackdrop').hidden = true; }); $('#modalBackdrop').addEventListener('click', (event) => { if (event.target.id === 'modalBackdrop') event.currentTarget.hidden = true; }); $('#postText').addEventListener('input', (event) => { $('#characterCount').textContent = `${event.target.value.length} / 280`; });
$('#publishButton').addEventListener('click', async () => { const text = $('#postText').value.trim(); if (!text) return showToast('Write something first'); try { await api.request('/posts', { method: 'POST', body: JSON.stringify({ text, image: selectedPostImage }) }); $('#postText').value = ''; $('#characterCount').textContent = '0 / 280'; $('#modalBackdrop').hidden = true; await loadApp(); showToast('Your story is live'); } catch (error) { showToast(error.message); } });
$('#postImageInput').addEventListener('change', async (event) => { const file = event.target.files[0]; if (!file) return; try { selectedPostImage = await resizeImage(file); $('#postImagePreview').src = selectedPostImage; $('#postImagePreview').hidden = false; $('#postImageLabel').textContent = file.name; } catch { showToast('That image could not be selected'); } });
function renderProfileEditor() { const user = state.user; const editorAvatar = $('#profileEditorAvatar'); editorAvatar.innerHTML = user.profileImage ? `<img src="${user.profileImage}" alt="${escapeHtml(user.name)} profile photo" />` : `<span>${user.initials}</span>`; editorAvatar.style.background = user.color; $('#profileNameInput').value = user.name; $('#profileHandleInput').value = user.handle; $('#profileBioInput').value = user.bio || ''; }
$('#profilePhotoEditor').addEventListener('click', () => $('#profileImageInput').click());
$('#profileImageInput').addEventListener('change', async (event) => { const file = event.target.files[0]; if (!file) return; try { const image = await resizeImage(file); const user = await api.request('/profile/image', { method: 'POST', body: JSON.stringify({ image }) }); setUser(user); renderProfileEditor(); await loadApp(); renderProfileEditor(); showToast('Profile photo updated'); } catch (error) { showToast(error.message); } });
$('#feed').addEventListener('click', async (event) => { const postElement = event.target.closest('[data-post-id]'); const menu = event.target.closest('.post-menu'); if (menu && postElement) { const post = state.posts.find((item) => item.id === postElement.dataset.postId); return openUtility('Post options', 'STORY MENU', `<p class="utility-copy">${escapeHtml(post.name)} · ${escapeHtml(post.handle)}</p><button class="sort-choice" id="copyPostLink"><strong>Copy post link</strong><span>Share this thought with someone</span></button><button class="sort-choice" id="reportPost"><strong>Report post</strong><span>Tell us if something feels off</span></button>`); } const button = event.target.closest('[data-action]'); if (!button || !postElement) return; const post = state.posts.find((item) => item.id === postElement.dataset.postId); const action = button.dataset.action; if (action === 'comment') return openComments(post); if (action === 'save') { const ids = savedIds(); const next = ids.includes(post.id) ? ids.filter((id) => id !== post.id) : [...ids, post.id]; localStorage.setItem('gather-saved', JSON.stringify(next)); renderFeed(); showToast(next.includes(post.id) ? 'Saved for later' : 'Removed from saved'); return; } try { await api.request(`/posts/${post.id}/${action}`, { method: 'POST' }); await loadApp(); showToast(action === 'like' ? 'Like updated' : 'Story link copied'); } catch (error) { showToast(error.message); } });
$('#searchInput').addEventListener('input', renderFeed);
document.querySelectorAll('.feed-tab').forEach((tab) => tab.addEventListener('click', () => { document.querySelectorAll('.feed-tab').forEach((item) => item.classList.remove('active')); tab.classList.add('active'); state.filter = tab.dataset.filter; $('#feedTitle').textContent = state.filter === 'following' ? 'From people you follow' : state.filter === 'latest' ? 'Latest stories' : 'Your daily mix'; renderFeed(); }));
$('#peopleList').addEventListener('click', async (event) => { const button = event.target.closest('[data-person]'); if (!button) return; try { await api.request(`/users/${button.dataset.person}/follow`, { method: 'POST' }); await loadApp(); showToast('Follow status updated'); } catch (error) { showToast(error.message); } });
$('#peopleList').addEventListener('click', (event) => { const button = event.target.closest('[data-message-person]'); if (!button) return; $('#chatDrawer').classList.add('open'); openConversation(button.dataset.messagePerson); });
async function openConversation(handle) { try { const data = await api.request(`/conversations/${handle}/messages`); state.selectedConversation = data.other; $('#chatEmpty').hidden = true; $('#messagePanel').hidden = false; $('#messageContact').innerHTML = `${avatar(data.other)} ${escapeHtml(data.other.name)} <span>${data.other.handle}</span>`; $('#messageList').innerHTML = data.messages.map((message) => `<div class="message-bubble ${message.mine ? 'mine' : ''}">${escapeHtml(message.text)}</div>`).join(''); renderConversations(); $('#messageList').scrollTop = $('#messageList').scrollHeight; } catch (error) { showToast(error.message); } }
async function syncInbox() { if (!api.token) return; try { const data = await api.request('/bootstrap'); state.conversations = data.conversations; renderConversations(); if (state.selectedConversation) await openConversation(state.selectedConversation.handle); } catch {} }
function startInboxPolling() { clearInterval(inboxTimer); inboxTimer = setInterval(syncInbox, 2000); }
document.querySelectorAll('[data-view]').forEach((item) => item.addEventListener('click', () => { const view = item.dataset.view; if (view === 'messages') { $('#chatDrawer').classList.add('open'); renderConversations(); return; } document.querySelectorAll('[data-view]').forEach((nav) => nav.classList.remove('active')); item.classList.add('active'); if (view === 'discover') { $('#feedTitle').textContent = 'Discover fresh perspectives'; state.filter = 'latest'; renderFeed(); } if (view === 'saved') { $('#feedTitle').textContent = 'Stories you saved'; const ids = savedIds(); renderFeed(state.posts.filter((post) => ids.includes(post.id))); } if (view === 'home') { $('#feedTitle').textContent = 'Your daily mix'; state.filter = 'for-you'; renderFeed(); } }));
$('#closeChat').addEventListener('click', () => $('#chatDrawer').classList.remove('open')); $('#conversationList').addEventListener('click', (event) => { const conversation = event.target.closest('[data-conversation]'); if (conversation) openConversation(conversation.dataset.conversation); });
$('#chatLaunch').addEventListener('click', () => { $('#chatDrawer').classList.add('open'); renderConversations(); });
$('#messageForm').addEventListener('submit', async (event) => { event.preventDefault(); const text = $('#messageInput').value.trim(); if (!text) return; if (!state.selectedConversation) return showToast('Select a person before sending'); try { await api.request(`/conversations/${state.selectedConversation.handle}/messages`, { method: 'POST', body: JSON.stringify({ text }) }); $('#messageInput').value = ''; await openConversation(state.selectedConversation.handle); } catch (error) { showToast(error.message); } });
$('#notificationButton').addEventListener('click', () => openUtility('Notifications', 'YOUR INBOX', '<div class="utility-item"><span class="utility-icon">♥</span><div><strong>Welcome to Gather</strong><p>Follow people and start conversations to see updates here.</p></div></div><div class="utility-item"><span class="utility-icon">✦</span><div><strong>Your feed is ready</strong><p>Share your first thought with the community.</p></div></div>'));
$('#viewProfile').addEventListener('click', () => { renderProfileEditor(); $('#profileBackdrop').hidden = false; $('#profileNameInput').focus(); });
$('#profileButton').addEventListener('click', () => { renderProfileEditor(); $('#profileBackdrop').hidden = false; $('#profileNameInput').focus(); });
$('#profileForm').addEventListener('submit', async (event) => { event.preventDefault(); try { const user = await api.request('/profile', { method: 'POST', body: JSON.stringify({ name: $('#profileNameInput').value, handle: $('#profileHandleInput').value, bio: $('#profileBioInput').value }) }); setUser(user); $('#profileBackdrop').hidden = true; showToast('Profile updated'); } catch (error) { showToast(error.message); } });
$('#closeProfileEditor').addEventListener('click', () => $('#profileBackdrop').hidden = true); $('#profileBackdrop').addEventListener('click', (event) => { if (event.target.id === 'profileBackdrop') event.currentTarget.hidden = true; });
$('#loadMore').addEventListener('click', () => showToast('You’re all caught up for now'));
$('#sortButton').addEventListener('click', () => openUtility('Sort your feed', 'FEED VIEW', '<button class="sort-choice" data-sort="curated"><strong>Curated</strong><span>Best conversations first</span></button><button class="sort-choice" data-sort="latest"><strong>Latest</strong><span>Newest posts first</span></button>'));
$('.create-space').addEventListener('click', () => openUtility('Create a space', 'YOUR SPACES', '<p class="utility-copy">Make a small place for a shared interest.</p><form id="spaceForm" class="utility-form"><input id="spaceName" placeholder="Space name" maxlength="30" required /><button class="post-button" type="submit">Create <span>↗</span></button></form>'));
$('.left-rail').addEventListener('click', (event) => { const spaceButton = event.target.closest('[data-space]'); if (spaceButton) openSpace(spaceButton.dataset.space); });
$('#utilityContent').addEventListener('click', (event) => { if (event.target.id === 'logoutButton') { localStorage.removeItem('gather-token'); location.reload(); } if (event.target.closest('[data-sort]')) { state.filter = event.target.closest('[data-sort]').dataset.sort === 'latest' ? 'latest' : 'for-you'; renderFeed(); closeUtility(); showToast('Feed order updated'); } });
$('#utilityContent').addEventListener('click', async (event) => { if (event.target.id === 'copyPostLink') { try { await navigator.clipboard.writeText(location.href); } catch {} closeUtility(); showToast('Post link copied'); } if (event.target.id === 'reportPost') { closeUtility(); showToast('Thanks, your report was recorded locally'); } const action = event.target.closest('[data-space-action]'); if (!action) return; const id = action.dataset.spaceId; if (action.dataset.spaceAction === 'join') { const joined = joinedSpaces(); const next = joined.includes(id) ? joined.filter((item) => item !== id) : [...joined, id]; localStorage.setItem('gather-joined-spaces', JSON.stringify(next)); closeUtility(); openSpace(id); showToast(next.includes(id) ? 'Joined space' : 'Left space'); } if (action.dataset.spaceAction === 'feed') { closeUtility(); const space = spaceCatalog[id]; $('#feedTitle').textContent = `${space ? space.name : 'Your'} space`; showToast('Space feed is ready for new conversations'); } });
$('#utilityContent').addEventListener('submit', (event) => { if (event.target.id !== 'spaceForm') return; event.preventDefault(); const colors = ['amber', 'coral', 'mint']; const spaces = JSON.parse(localStorage.getItem('gather-spaces') || '[]'); spaces.push({ id: `custom-${Date.now()}`, name: $('#spaceName').value.trim(), description: 'A new place to gather around a shared interest.', members: 1, color: colors[spaces.length % colors.length] }); localStorage.setItem('gather-spaces', JSON.stringify(spaces)); renderSpaces(); closeUtility(); showToast('Space created'); });
$('#closeUtility').addEventListener('click', closeUtility); $('#utilityBackdrop').addEventListener('click', (event) => { if (event.target.id === 'utilityBackdrop') closeUtility(); });
function openComments(post) { $('#commentTitle').textContent = `${post.comments} comments`; $('#commentList').innerHTML = '<p class="empty-comments">Be the first to add a thoughtful reply.</p>'; $('#commentBackdrop').hidden = false; $('#commentInput').focus(); state.commentPost = post; }
$('#commentForm').addEventListener('submit', async (event) => { event.preventDefault(); const text = $('#commentInput').value.trim(); if (!text) return; try { await api.request(`/posts/${state.commentPost.id}/comments`, { method: 'POST', body: JSON.stringify({ text }) }); $('#commentInput').value = ''; await loadApp(); $('#commentBackdrop').hidden = true; showToast('Comment added'); } catch (error) { showToast(error.message); } });
$('#closeComment').addEventListener('click', () => $('#commentBackdrop').hidden = true); $('#commentBackdrop').addEventListener('click', (event) => { if (event.target.id === 'commentBackdrop') event.currentTarget.hidden = true; });
$('#seeAllPeople').addEventListener('click', () => openUtility('People to follow', 'DISCOVER', state.people.map((person) => `<div class="utility-item">${avatar(person)}<div><strong>${escapeHtml(person.name)}</strong><p>${escapeHtml(person.bio || person.note || '')}</p></div></div>`).join('')));
$('.more-button').addEventListener('click', () => openUtility('Trending today', 'WHAT PEOPLE ARE TALKING ABOUT', '<div class="utility-item"><div><strong>#slowdesign</strong><p>2,430 conversations about making space for better ideas.</p></div></div><div class="utility-item"><div><strong>#thelongread</strong><p>1,982 conversations from readers and writers.</p></div></div><div class="utility-item"><div><strong>#offthegrid</strong><p>846 conversations about finding a little quiet.</p></div></div>'));
$('#themeToggle').addEventListener('click', () => { const theme = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('gather-theme', theme); applyTheme(theme); });
if (api.token) loadApp().then(startInboxPolling).catch(() => { localStorage.removeItem('gather-token'); api.token = null; });
